### ISSUE TITLE
CC0?

### ISSUE THREAD

**Issue by jaekwon** [cosmos/ics#124]
I'm seeing some CC0 licenses, but we should probably pull all references to those and maybe replace them with Apache2.0 for now.

https://opensource.stackexchange.com/questions/133/how-could-using-code-released-under-cc0-infringe-on-the-authors-patents

Even though most of it is spec work, it would be better to be clear about the patent rights of things developed here, and Apache2.0 makes it clearer than CC0.

**Comment by cwgoes** [comment]
CC0 was chosen as it is used by [EIPs](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1.md#copyright) - we could certainly make a different choice though. I wonder if Ethereum has thought about the patent question, and what conclusions they came to which led to the choice of CC0.

**Comment by cwgoes** [comment]
Concurred that this is fine in meeting.
