### ISSUE TITLE
Ordered / unordered channels

### ISSUE THREAD

**Issue by cwgoes** [cosmos/ics#132]
Split off from #126. Would be superseded by #131 if we implement that. Otherwise,

- Add unordered channels, with timeout semantics as they currently are
- Alter ordered channels so that timeouts (of any packet) immediately close ordered channels

**Comment by cwgoes** [comment]
Unordered channels will need an accumulator to track received packets. It can just store a hash though.

**Comment by cwgoes** [comment]
We could still keep the maximum index before which all packets have been received.

**Comment by mossid** [comment]
> We could still keep the maximum index before which all packets have been received

```go
func receivePacketUnordered(packet Packet) {
  allpacketmax := readMaximuimIndexAllPacketReceived()
  if allpacketmax + 1 != packet.Index {
    setPacketReceived(packet.Index)
    return
  }
  for rpacket := range packetReceivedPrefix.Iterate() {
    if rpacket.Index != allpacketmax + 1 {
      break
    }
    allpacketmax += 1
    deletePacketReceived(rpacket.Index)
  }
  setMaximumIndexAllPacketReceived(allpacketmax)
}
```

**Comment by cwgoes** [comment]
> in this way any packet sent unordered are marked as sent(setPacketReceived) individually onchain and pruned once the maximum index catches it

Yes, that would be the idea. I am a bit concerned about the iteration on-chain however. 

Better to have the relayer provide start / end indices of packets to be cleaned up and the chain just verifies that they have all been received (and `cleanupReceived` should be separate from `recvPacket`).
