### ISSUE TITLE
Channel Handshake might not be needed because of ICS 5

### ISSUE THREAD

**Issue by mossid** [cosmos/ics#153]
Connection handshake process is to prevent another chain pretending the counterparty, and Channel handshake process is to prevent another "module"/port pretending the counterparty. If the capability keys to access on the ports are protected by the objcap principles, other modules cannot access on the counterparty ports, so the ICS 5 may already achieve this goal.

Category: Fix suggestion on spec
Object: ICS 4

**Comment by cwgoes** [comment]
The problem as I see it is race conditions between opening two channels on the same port with the same identifier - if you don't have a handshake, and two modules on two blockchains A & B open the same channel identifier to the same port on some chain C, and start (optimistically, since there was no handshake) sending packets on it (and e.g. burning coins), what happens?

**Comment by mossid** [comment]
If we are storing the port owner in the state, we can add the desired counterparty port in it too. The other chain can inspect the state to check whether the port it is trying to connect has itself as its counterparty, so we can omit the handshake process?

**Comment by cwgoes** [comment]
> If we are storing the port owner in the state, we can add the desired counterparty port in it too. The other chain can inspect the state to check whether the port it is trying to connect has itself as its counterparty, so we can omit the handshake process?

How does that help with the race condition case? Both chains `A` and `B` might be able to inspect and check that a channel could be opened to `C`, but they could still try to open it at the same time.

**Comment by mossid** [comment]
That's right, I forgot that channelKey is no longer dependent on the connection id(in that case channel ids will be unique per connection so two different chains cannot connect to a same channel).

**Comment by cwgoes** [comment]
> That's right, I forgot that channelKey is no longer dependent on the connection id(in that case channel ids will be unique per connection so two different chains cannot connect to a same channel).

Ah right, yes; that used to be the case but it isn't any longer.
