### ISSUE TITLE
ICS ?: IBC threat model & security assumptions

### ISSUE THREAD

**Issue by cwgoes** [cosmos/ics#2]
Primarily a port of [the original IBC spec](https://github.com/cosmos/cosmos-sdk/tree/develop/docs/spec/ibc).

Will cover:
- Security assumptions of the underlying consensus
- Required slashing conditions / evidence handling
- Exceptional cases and possible recovery methods

**Comment by mossid** [comment]
I think `Security assumption` can be merged into #25, `Exceptional cases and recovery methods` can be merged into #6, and `slashing conditions / evidence handling` should be merged into #10 and separated into a new issue, perhaps `IBC slashing module` on Application layer section.

**Comment by cwgoes** [comment]
> I think `Security assumption` can be merged into #25, `Exceptional cases and recovery methods` can be merged into #6, and `slashing conditions / evidence handling` can be merged into #10 and separated into a new issue, perhaps `validator remote slashing` on Application layer section.

Perfect, done.
