### ISSUE TITLE
ICS 5: IBC packet semantics & handling

### ISSUE THREAD

**Issue by cwgoes** [cosmos/ics#24]
Primarily ported from the [original IBC spec](https://github.com/cosmos/cosmos-sdk/blob/develop/docs/spec/ibc/channels-and-packets.md#321-packet).

Will cover:
- IBC packet semantics
- Required data structures
- Packet wire encoding

**Comment by cwgoes** [comment]
To-do in spec:
- Reference primitives defined in ICS 3 / ICS 4
- Formalize packet handling algorithm
- Enumerate security properties (particularly replay prevention)
- Define packet data structure
- Define options for receipts, timeouts, alterations to handlers

**Comment by cwgoes** [comment]
Datagram formats that need to be defined in this spec (that I can think of so far):

- `PACKETFORWARD` - forward packet
- `PACKETREVERSE` - reverse packet (receipt)
- `PACKETTIMEOUT` - timeout packet (if it needs to be a packet at all)

**Comment by mossid** [comment]
My thought was directly inspecting the incoming sequence on the other chain to detect timeout, so in that case, `PACKETTIMEOUT` will not be needed.

**Comment by cwgoes** [comment]
I think that depends on which ordering requirements are selected by the channel - sometimes one might want timeouts without ordering - but when possible I agree.

**Comment by cwgoes** [comment]
Possibly this may not actually require a separate ICS, I think ICS 4 will determine most of this at the channel level.

**Comment by cwgoes** [comment]
Closing, this should just be merged into ICS 4 (https://github.com/cosmos/ics/issues/1).
