### ISSUE TITLE
ICS 19: Standard queue

### ISSUE THREAD

**Issue by cwgoes** [cosmos/ics#39]
Partially ported from [the original spec](https://github.com/cosmos/cosmos-sdk/blob/develop/docs/spec/ibc/channels-and-packets.md#323-queue).

**Comment by mossid** [comment]
A possible encoding scheme for the indices and `q_head q_tail`:
- `encode :: index uint64 | Head | Tail -> bytes`
- `encode(index uint64) -> bigendian64(index)`
- `encode(Head) -> bigendian64(int64_max) ++ 0x00`
- `encode(Tail) -> bigendian64(int64_max) ++ 0x01`

**Comment by cwgoes** [comment]
We don't actually need a queue - fancy that!
