### ISSUE TITLE
IBC definitions

### ISSUE THREAD

**Issue by cwgoes** [cosmos/ics#49]
Just noting for clarity so we avoid using the same term to mean different things in different places.

**Ledger / Chain**

A *ledger*, or *chain*, is a distributed ledger (or "blockchain", although a strict chain of blocks may not be required) implementing part or all of the IBC specification as a component or module within its state machine.

**Handler**

An IBC *handler* is the module or subcomponent within the state machine of a ledger responsible for implementing the IBC specification by "handling" datagrams, performing the appropriate checks, proof verifications,  and/or storage alterations, and routing valid packets to other parts of the state machine, as defined by the application-layer semantics.

**Datagram**

A *datagram* is an opaque data blob transmitted over some network, and handled by the top-level IBC handler implemented in the ledger's state machine. In some implementations, the datagram may be a field in a ledger-specific transaction or message data structure which also contains other information (e.g. a fee for spam prevention, nonce for replay prevention, type identifier to route to the IBC handler, etc.)

**Connection**

A *connection* is a persistent data structure on a particular ledger that contains information about the consensus state of another ledger. Updates to that consensus state change the state of the connection.

**Channel**

A *channel* is a persistent data structure on a particular ledger that contains metadata to facilitate packet ordering, exactly-once delivery, and replay prevention. Often it may make sense to reason about a "channel" across two chains (reasoning about subsets of state on both ledgers).

**Packet** 

A *packet* is a particular data structure with sequence-related metadata (defined by the IBC specification) and an opaque value field (with semantics defined by the application layer).

**Comment by Liamsi** [comment]
Suggestion / Question: If this informal overview will be included in sth. else than this issue (?), the definitions should be re-ordered. e.g., if a Datagram is more general than a Packet it should come later (and that relation should explicitly be mentioned). Similarly, as a handler handles Datagrams it should be described after Datagrams.
