### ISSUE TITLE
IBC statement of purpose

### ISSUE THREAD

**Issue by cwgoes** [cosmos/ics#51]
Somewhere we should have a document outlining, at a high level, the purpose, design goals, and scope of IBC, and linking to the different subcomponents. This document should be designed to be read by someone who has some background in blockchains but none with Tendermint/Cosmos or IBC.

This isn't a technical specification, so I don't think it should go in this repository. Maybe it should be a page on the Cosmos or Interchain website - the closest kind of document to what I'm envisioning is the [What is Cosmos](https://cosmos.network/intro) page on the Cosmos Network website (which has a section on IBC, but not a comprehensive breakdown).

**Comment by ebuchman** [comment]
> This isn't a technical specification, so I don't think it should go in this repository.

In so far as it will facilitate people diving into the specs in this repo, I think it's fine if there's a high level overview included here, especially if it can give context and reference to the ICS components

**Comment by cwgoes** [comment]
> > This isn't a technical specification, so I don't think it should go in this repository.
> 
> In so far as it will facilitate people diving into the specs in this repo, I think it's fine if there's a high level overview included here, especially if it can give context and reference to the ICS components

Yes; Agoric thought so as well, maybe we should add that to the README or at least linked from it. I can write something up for feedback.
