### ISSUE TITLE
LaTeX typesetting of algorithms

### ISSUE THREAD

**Issue by cwgoes** [cosmos/ics#62]
I think I have come up with a reasonable way of typesetting LaTeX structure definitions, procedures, and equations and embedding the generated images in Markdown in https://github.com/cosmos/ics/pull/32.

The generated images look something like this:

![Example](https://media.githubusercontent.com/media/cosmos/ics/cwgoes/ics-3-connection-semantics/spec/ics-3-connection-semantics/header_tracking.png)

The LaTeX is reasonably easy to write and it makes for much cleaner algorithmic descriptions than are possible in vanilla GitHub Markdown. If others are in agreement, I would like to standardize the resulting LaTeX templates, styles, and Makefile to be used across all interchain standards which require such definitions. 

Thoughts?

**Comment by cwgoes** [comment]
@cwgoes to add: LaTeX template for "protocol flow" table, ref https://github.com/cosmos/ics/pull/32/commits/5146a14958a1195881d4b01f613ad36f14360d0e

**Comment by milosevic** [comment]
I strongly support this idea. If we have convincing proposal, would most probably replicate it to Tendermint as I think that current spec renders really bad (good part written by me :)).

**Comment by cwgoes** [comment]
Ref https://github.com/cosmos/ics/issues/67

A lot of valid concerns were raised regarding reviewability of LaTeX in diff form.
