### ISSUE TITLE
Figure out best syntactical format for specifications and write meta-protocol

### ISSUE THREAD

**Issue by cwgoes** [cosmos/ics#67]
Per suggestion from @milosevic.

Also includes English guidelines ("natural compiler"):
- Define terms before usage
- Move motivation out of "Specification"
- Add top-level architecture document to define basic set of terms

Other notes
- Split handleDatagram into sub-functions (likewise for other functions)
- Keep pseudcode snippets short
- Try CoffeeScript/Golang snippets instead of Markdown
- Define pseudocode keywords in meta-spec
- Include proto3 encoding file
- Include state machine descriptions
- Express IBC as protocol between modules on blockchains
- First include definitions of communications channels
- "Requirements" section can only use previously defined terms
- Subprotocol definitions include concrete message types, processing behavior

Clear technical reports
- Paxos original paper
- TCP specification

Other ideas
- Executable spec for protocol conformance
- Standard / reference testsuite + fuzzer

*Try this* with ICS 2 / 3.

**Comment by cwgoes** [comment]
- Split handleDatagram into sub-functions

**Comment by cwgoes** [comment]
Example layout:

1. INTRODUCTION
1.1. Motivation
1.2. Scope
1.3. About this Document
1.4. Interfaces
1.5. Operation

2. PHILOSOPHY
2.1. Elements of the Interconected Blockchain System
2.2. Model of Operation
2.4. Interfaces
2.5. Relation to Other Protocols/ Modules/ Apps
2.6. Connection Establishment and Clearing
2.8. Data Communication
2.9. Precedence and Security
2.10. Robustness Principle

3. FUNCTIONAL SPECIFICATION
3.1. Header Format
3.4. Establishing a connection
3.5. Closing a Connection
3.7. Data Communication
3.8. Interfaces
3.9. Event Processing

**Comment by mossid** [comment]
Some RFCs:
* RFC 2119: https://www.ietf.org/rfc/rfc2119.txt / definitions on "may", "should", "must", etc.
* RFC 793: https://tools.ietf.org/html/rfc793 / tcp spec
* RFC Best current practices: https://en.wikipedia.org/wiki/Best_current_practice

**Comment by cwgoes** [comment]
https://github.com/cosmos/ics/pull/68 defines a bunch of terms.

**Comment by cwgoes** [comment]
https://github.com/cosmos/ics/pull/70 is a start at a high-level protocol explanation a la the TCP RFC.

**Comment by cwgoes** [comment]
We're now using RFC 2119 and have a standard set of sections in each specification.

Requests for any meta-level changes are welcome in followup issues.
