### ISSUE TITLE
ICS 19-KVStore: KVStore Queue 

### ISSUE THREAD

**Issue by mossid** [cosmos/ics#73]
ICS19-KVStore is a concrete specification which fulfills ICS19 on KVStore. 

`KVStore` is a set of data structures(needs a separated ICS) which satisfies:
- Is a Merkle tree
- "Efficient" iteration on the keys

ICS19-KVStore defines the following:
- Big endian encoding of the indices, which is compatible with KVStore iteration
- `q_head` and `q_tail` key encoding which does not collide with index encoding
- Queue operations, including `peek`, `pop`, `retrieve`, `push`, `advance`

(I'm not sure if this have to be a part of ICS19 main spec, key encodings looks general for most of the accumulator types)

**Comment by cwgoes** [comment]
I don't think we actually need most of these operations, we just need sequencing, for which associating each packet with a counter and storing the current counter is sufficient.

Let's not define anything more than absolutely necessary. I'm not actually sure this warrants an ICS.

**Comment by cwgoes** [comment]
@mossid and I determined that we don't need a full queue structure, just a key format and a monotonically incrementing counter, so this can be merged into ICS 4.
