### ISSUE TITLE
Reorganize sections for clarity

### ISSUE THREAD

**Issue by cwgoes** [cosmos/ics#84]
Ref https://github.com/cosmos/ics/pull/20/files#r279727245

(we should do this consistently across specs)

**Comment by cwgoes** [comment]
Also change `#` to `##` (and all subsequent levels likewise)

**Comment by gamarin2** [comment]
why close?

**Comment by cwgoes** [comment]
> why close?

Because I made the modifications you requested on master, and noted this issue on outstanding PRs.

**Comment by gamarin2** [comment]
It's just that I've seen many PRs where the changes have not been made yet. If this PR is closed we might forget to actually make the change on the PRs

**Comment by cwgoes** [comment]
Ok!

**Comment by cwgoes** [comment]
(this is now checked automatically in CI)
