### ISSUE TITLE
Finite state machine visual diagramming

### ISSUE THREAD

**Issue by cwgoes** [cosmos/ics#88]
Although it's lower-priority, I think it would be helpful to have visual depictions of state machines involved in the interblockchain communication protocol, especially where multi-step handshakes or complex causal chains are involved.

I'm not sure what the best software is for this. [Draw.io](https://about.draw.io/uml-state-diagrams-with-draw-io/) seems to support the right sort of visualizations, but I'm not sure there would be an output source file. Ideally we could include source LaTeX or something with the specs.

Open to ideas.

cc @ancazamfir

**Comment by ancazamfir** [comment]
We could start with an ASCII one (ala RFCs) and decide on a tool in parallel. If you need, I can help with it if you send out a hand drawn diagram.

**Comment by cwgoes** [comment]
> We could start with an ASCII one (ala RFCs) and decide on a tool in parallel. If you need, I can help with it if you send out a hand drawn diagram.

Thanks - I'm not actually sure ASCII diagrams will be less work, I'll play around.

Alternatively I could take pictures of whiteboards, but unfortunately there would be no source to edit.

**Comment by cwgoes** [comment]
What about:

![example](https://media.githubusercontent.com/media/cosmos/ics/cwgoes/ics-3-connection-semantics/spec/ics-3-bidirectional-connection-semantics/state.png)

**Comment by cwgoes** [comment]
This is easier than I thought it would be, let's do it for all multi-step state machines in the protocol.

**Comment by cwgoes** [comment]
I think LaTeX diagrams will work for now, the syntax isn't hard to learn and the output looks decent.
