### ISSUE TITLE
First MVP implementation in the Cosmos SDK (Golang)

### ISSUE THREAD

**Issue by cwgoes** [cosmos/ics#95]
- Implement ICS 2, 3, 4, 18, 23, 24, 25, exposing a full interface to module developers.
- Light client logic can be "faked" for now, the goal is more to play with the interface.

**Comment by cwgoes** [comment]
In progress [here](https://github.com/cosmos/cosmos-sdk/tree/joon/ics-implementation).

**Comment by cwgoes** [comment]
Functional-ish at Hackatom Berlin (thanks @mossid) - concluded to polish this and merge as a reference implementation with a warning that further changes are expected prior to real-world deployment.

**Comment by mossid** [comment]
SDK side issue is here: https://github.com/cosmos/cosmos-sdk/issues/4723

**Comment by cwgoes** [comment]
Closing in favor of https://github.com/cosmos/ics/issues/145.
